<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nShd0Fa' shared service.

return $this->privates['.service_locator.nShd0Fa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\DefaultController::salvar' => ['privates', '.service_locator.RHQ_J_P', 'get_ServiceLocator_RHQJPService.php', true],
    'App\\Controller\\DefaultController:salvar' => ['privates', '.service_locator.RHQ_J_P', 'get_ServiceLocator_RHQJPService.php', true],
], [
    'App\\Controller\\DefaultController::salvar' => '?',
    'App\\Controller\\DefaultController:salvar' => '?',
]);
