<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RHQ_J_P' shared service.

return $this->privates['.service_locator.RHQ_J_P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'fecha' => ['privates', '.errored..service_locator.RHQ_J_P.DateTime', NULL, 'Cannot autowire service ".service_locator.RHQ_J_P": it references class "DateTime" but no such service exists.'],
], [
    'fecha' => 'DateTime',
]);
