<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5izC8J8\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5izC8J8/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container5izC8J8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container5izC8J8\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container5izC8J8\srcApp_KernelProdContainer([
    'container.build_hash' => '5izC8J8',
    'container.build_id' => '65b8e29b',
    'container.build_time' => 1570913788,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5izC8J8');
