<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'entrar' => [[], ['_controller' => 'App\\Controller\\DashboardController::entrar'], [], [['text', '/entrar']], [], []],
    'editar_talleres' => [[], ['_controller' => 'App\\Controller\\DashboardController::editar'], [], [['text', '/dashboard/editar']], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], []],
    'inicio' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'articulo_nuevo' => [[], ['_controller' => 'App\\Controller\\DefaultController::salvar'], [], [['text', '/salvar/articulo']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
