<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9XHO0tI' shared service.

return $this->privates['.service_locator.9XHO0tI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
], [
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
