<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5HdRZP8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5HdRZP8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5HdRZP8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5HdRZP8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5HdRZP8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5HdRZP8',
    'container.build_id' => '9cffe350',
    'container.build_time' => 1570979582,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5HdRZP8');
