<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4qZwN1U\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4qZwN1U/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4qZwN1U.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4qZwN1U\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4qZwN1U\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4qZwN1U',
    'container.build_id' => 'c869d02f',
    'container.build_time' => 1570917522,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4qZwN1U');
